use crate::model::SystemReport;
use std::fmt::Write as _;

pub fn render_text(report: &SystemReport) -> String {
    let mut out = String::new();

    let _ = writeln!(out, "╔══════════════════════════════════════════════════════════════╗");
    let _ = writeln!(out, "║                            HowAmI                            ║");
    let _ = writeln!(out, "║              Computer Hardware & System Report              ║");
    let _ = writeln!(out, "╚══════════════════════════════════════════════════════════════╝");
    let _ = writeln!(out);
    let _ = writeln!(out, "Generated At         : {}", report.meta.generated_at);
    let _ = writeln!(out, "Version              : {}", report.meta.app_version);
    let _ = writeln!(out, "Report Schema        : {}", report.meta.schema_version);
    let _ = writeln!(out, "OS                   : {}", report.meta.os);
    let _ = writeln!(out, "Architecture         : {}", report.meta.architecture);
    let _ = writeln!(
        out,
        "Collection Privilege : {}",
        if report.meta.elevated {
            "Administrator / root"
        } else {
            "Standard user"
        }
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "Privacy / 개인정보: {}", report.meta.privacy_notice);

    if !report.warnings.is_empty() {
        let _ = writeln!(out);
        let _ = writeln!(out, "[ WARNINGS / 경고 ]");
        for warning in &report.warnings {
            let _ = writeln!(out, "- {warning}");
        }
    }

    for section in &report.sections {
        let _ = writeln!(out);
        let _ = writeln!(out, "==============================================================");
        let _ = writeln!(out, "[ {} ]", section.name);
        let _ = writeln!(out, "==============================================================");

        if section.records.is_empty() {
            let _ = writeln!(out, "Not available / 데이터 없음");
            continue;
        }

        for (index, record) in section.records.iter().enumerate() {
            if index > 0 {
                let _ = writeln!(out);
            }
            let _ = writeln!(out, "-- {} --", record.label);

            if record.fields.is_empty() {
                let _ = writeln!(out, "Not available / 데이터 없음");
                continue;
            }

            let width = record
                .fields
                .keys()
                .map(|key| key.chars().count())
                .max()
                .unwrap_or(0)
                .min(36);

            for (key, value) in &record.fields {
                let display = display_value(&section.name, key, value);
                let _ = writeln!(out, "{key:width$} : {display}", width = width);
            }
        }
    }

    let _ = writeln!(out);
    let _ = writeln!(out, "Generated by HowAmI — Silverbell Choir");
    out
}

fn display_value(section: &str, key: &str, value: &str) -> String {
    if is_byte_field(section, key) {
        if let Ok(bytes) = value.trim().parse::<u64>() {
            return format!("{value} ({})", format_bytes(bytes));
        }
    }

    if key == "SpeedBitsPerSecond" {
        if let Ok(bits_per_second) = value.trim().parse::<u64>() {
            return format!(
                "{value} ({})",
                format_bits_per_second(bits_per_second)
            );
        }
    }

    value.to_string()
}

fn is_byte_field(section: &str, key: &str) -> bool {
    key.ends_with("Bytes")
        || key == "VRAMBytes"
        || (section == "Storage" && key.eq_ignore_ascii_case("size"))
}

fn format_bytes(bytes: u64) -> String {
    const KIB: f64 = 1024.0;
    const MIB: f64 = KIB * 1024.0;
    const GIB: f64 = MIB * 1024.0;
    const TIB: f64 = GIB * 1024.0;
    let value = bytes as f64;

    if value >= TIB {
        format!("{:.2} TiB", value / TIB)
    } else if value >= GIB {
        format!("{:.2} GiB", value / GIB)
    } else if value >= MIB {
        format!("{:.2} MiB", value / MIB)
    } else if value >= KIB {
        format!("{:.2} KiB", value / KIB)
    } else {
        format!("{bytes} B")
    }
}

fn format_bits_per_second(bits: u64) -> String {
    let value = bits as f64;
    if value >= 1_000_000_000.0 {
        format!("{:.2} Gbit/s", value / 1_000_000_000.0)
    } else if value >= 1_000_000.0 {
        format!("{:.2} Mbit/s", value / 1_000_000.0)
    } else if value >= 1_000.0 {
        format!("{:.2} kbit/s", value / 1_000.0)
    } else {
        format!("{bits} bit/s")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{DeviceRecord, ReportMeta, Section, SystemReport};

    fn sample_report() -> SystemReport {
        let mut cpu = Section::new("CPU");
        cpu.push(DeviceRecord::new("CPU 0").with_field("Model", "Example CPU"));
        SystemReport {
            meta: ReportMeta {
                schema_version: 1,
                app_name: "HowAmI".into(),
                app_version: "0.1.0".into(),
                generated_at: "2026-01-01T00:00:00+00:00".into(),
                os: "test".into(),
                architecture: "x86_64".into(),
                elevated: true,
                privacy_notice: "test".into(),
            },
            sections: vec![cpu],
            warnings: vec![],
        }
    }

    #[test]
    fn text_report_contains_core_fields() {
        let text = render_text(&sample_report());
        assert!(text.contains("HowAmI"));
        assert!(text.contains("Report Schema        : 1"));
        assert!(text.contains("Example CPU"));
        assert!(text.contains("Collection Privilege : Administrator / root"));
    }

    #[test]
    fn formats_byte_counts_for_people() {
        assert_eq!(
            display_value("GPU Memory (Registry)", "VRAMBytes", "8589934592"),
            "8589934592 (8.00 GiB)"
        );
        assert_eq!(
            display_value("Storage", "size", "1099511627776"),
            "1099511627776 (1.00 TiB)"
        );
    }

    #[test]
    fn formats_network_bit_rate() {
        assert_eq!(
            display_value("Network Adapters", "SpeedBitsPerSecond", "1000000000"),
            "1000000000 (1.00 Gbit/s)"
        );
    }
}
