use crate::model::SystemReport;
use std::fmt::Write as _;

pub fn render_text(report: &SystemReport) -> String {
    let mut out = String::new();

    let _ = writeln!(out, "╔══════════════════════════════════════════════════════════════╗");
    let _ = writeln!(out, "║                            HowAmI                            ║");
    let _ = writeln!(out, "║              Computer Hardware & System Report              ║");
    let _ = writeln!(out, "╚══════════════════════════════════════════════════════════════╝");
    let _ = writeln!(out);
    let _ = writeln!(out, "Generated At : {}", report.meta.generated_at);
    let _ = writeln!(out, "Version      : {}", report.meta.app_version);
    let _ = writeln!(out, "OS           : {}", report.meta.os);
    let _ = writeln!(out, "Architecture : {}", report.meta.architecture);
    let _ = writeln!(
        out,
        "Privilege    : {}",
        if report.meta.elevated {
            "Administrator / root"
        } else {
            "Standard user"
        }
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "Privacy / 개인정보: {}", report.meta.privacy_notice);

    if !report.warnings.is_empty() {
        let _ = writeln!(out);
        let _ = writeln!(out, "[ WARNINGS / 경고 ]");
        for warning in &report.warnings {
            let _ = writeln!(out, "- {warning}");
        }
    }

    for section in &report.sections {
        let _ = writeln!(out);
        let _ = writeln!(out, "==============================================================");
        let _ = writeln!(out, "[ {} ]", section.name);
        let _ = writeln!(out, "==============================================================");

        if section.records.is_empty() {
            let _ = writeln!(out, "Not available / 데이터 없음");
            continue;
        }

        for (index, record) in section.records.iter().enumerate() {
            if index > 0 {
                let _ = writeln!(out);
            }
            let _ = writeln!(out, "-- {} --", record.label);

            if record.fields.is_empty() {
                let _ = writeln!(out, "Not available / 데이터 없음");
                continue;
            }

            let width = record
                .fields
                .keys()
                .map(|key| key.chars().count())
                .max()
                .unwrap_or(0)
                .min(36);

            for (key, value) in &record.fields {
                let _ = writeln!(out, "{key:width$} : {value}", width = width);
            }
        }
    }

    let _ = writeln!(out);
    let _ = writeln!(out, "Generated by HowAmI — Silverbell Choir");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{DeviceRecord, ReportMeta, Section, SystemReport};

    #[test]
    fn text_report_contains_core_fields() {
        let mut cpu = Section::new("CPU");
        cpu.push(DeviceRecord::new("CPU 0").with_field("Model", "Example CPU"));
        let report = SystemReport {
            meta: ReportMeta {
                app_name: "HowAmI".into(),
                app_version: "0.1.0".into(),
                generated_at: "2026-01-01T00:00:00+00:00".into(),
                os: "test".into(),
                architecture: "x86_64".into(),
                elevated: true,
                privacy_notice: "test".into(),
            },
            sections: vec![cpu],
            warnings: vec![],
        };

        let text = render_text(&report);
        assert!(text.contains("HowAmI"));
        assert!(text.contains("Example CPU"));
        assert!(text.contains("Administrator / root"));
    }
}
