use crate::model::SystemReport;
use std::fmt::Write as _;

pub fn render_text(report: &SystemReport) -> String {
    let mut out = String::new();

    let _ = writeln!(
        out,
        "╔══════════════════════════════════════════════════════════════╗"
    );
    let _ = writeln!(
        out,
        "║                            HowAmI                            ║"
    );
    let _ = writeln!(
        out,
        "║              Computer Hardware & System Report              ║"
    );
    let _ = writeln!(
        out,
        "╚══════════════════════════════════════════════════════════════╝"
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "Generated At         : {}", report.meta.generated_at);
    let _ = writeln!(out, "Version              : {}", report.meta.app_version);
    let _ = writeln!(out, "Report Schema        : {}", report.meta.schema_version);
    let _ = writeln!(out, "OS                   : {}", report.meta.os);
    let _ = writeln!(out, "Architecture         : {}", report.meta.architecture);
    let _ = writeln!(
        out,
        "Collection Privilege : {}",
        if report.meta.elevated {
            "Administrator / root"
        } else {
            "Standard user"
        }
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "Privacy / 개인정보: {}", report.meta.privacy_notice);

    if !report.warnings.is_empty() {
        let _ = writeln!(out);
        let _ = writeln!(out, "[ WARNINGS / 경고 ]");
        for warning in &report.warnings {
            let _ = writeln!(out, "- {warning}");
        }
    }

    for section in &report.sections {
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "=============================================================="
        );
        let _ = writeln!(out, "[ {} ]", section.name);
        let _ = writeln!(
            out,
            "=============================================================="
        );

        if section.records.is_empty() {
            let _ = writeln!(out, "Not available / 데이터 없음");
            continue;
        }

        for (index, record) in section.records.iter().enumerate() {
            if index > 0 {
                let _ = writeln!(out);
            }
            let _ = writeln!(out, "-- {} --", record.label);

            if record.fields.is_empty() {
                let _ = writeln!(out, "Not available / 데이터 없음");
                continue;
            }

            let width = record
                .fields
                .keys()
                .map(|key| key.chars().count())
                .max()
                .unwrap_or(0)
                .min(36);

            for (key, value) in &record.fields {
                let display = display_value(&section.name, key, value);
                let _ = writeln!(out, "{key:width$} : {display}", width = width);
            }
        }
    }

    let _ = writeln!(out);
    let _ = writeln!(out, "Generated by HowAmI — Silverbell Choir");
    out
}

fn display_value(section: &str, key: &str, value: &str) -> String {
    if is_byte_field(section, key) {
        if let Ok(bytes) = value.trim().parse::<u64>() {
            return format!("{value} ({})", format_bytes(bytes));
        }
    }

    if key == "SpeedBitsPerSecond" {
        if let Ok(bits_per_second) = value.trim().parse::<u64>() {
            return format!("{value} ({})", format_bits_per_second(bits_per_second));
        }
    }

    if section == "Network Adapters" && key == "speed" {
        if let Ok(megabits) = value.trim().parse::<u64>() {
            return if megabits >= 1000 {
                format!("{value} Mbit/s ({:.2} Gbit/s)", megabits as f64 / 1000.0)
            } else {
                format!("{value} Mbit/s")
            };
        }
    }

    if section == "Hardware Sensors / hwmon" {
        if let Some(display) = format_hwmon_value(key, value) {
            return display;
        }
    }

    if section == "Power / Battery" {
        if let Some(display) = format_power_supply_value(key, value) {
            return display;
        }
    }

    if let Ok(code) = value.trim().parse::<u32>() {
        let label = match key {
            "ArchitectureCode" => processor_architecture_name(code),
            "MemoryTypeCode" => cim_memory_type_name(code),
            "SMBIOSMemoryTypeCode" => smbios_memory_type_name(code),
            "FormFactorCode" => memory_form_factor_name(code),
            _ => None,
        };
        if let Some(label) = label {
            return format!("{value} ({label})");
        }
    }

    value.to_string()
}

fn is_byte_field(section: &str, key: &str) -> bool {
    key.ends_with("Bytes") || (section == "Storage" && key.eq_ignore_ascii_case("size"))
}

fn format_hwmon_value(key: &str, value: &str) -> Option<String> {
    let raw = value.trim().parse::<i64>().ok()?;

    if key.starts_with("temp") && key.ends_with("_input") {
        return Some(format!("{value} ({:.2} °C)", raw as f64 / 1000.0));
    }
    if key.starts_with("fan") && key.ends_with("_input") {
        return Some(format!("{value} RPM"));
    }
    if key.starts_with("in") && key.ends_with("_input") {
        return Some(format!("{value} ({:.3} V)", raw as f64 / 1000.0));
    }
    if key.starts_with("curr") && key.ends_with("_input") {
        return Some(format!("{value} ({:.3} A)", raw as f64 / 1000.0));
    }
    if key.starts_with("power")
        && (key.ends_with("_input") || key.ends_with("_average") || key.ends_with("_highest"))
    {
        return Some(format!("{value} ({:.3} W)", raw as f64 / 1_000_000.0));
    }
    if key.starts_with("energy") && key.ends_with("_input") {
        return Some(format!("{value} ({:.3} J)", raw as f64 / 1_000_000.0));
    }
    if key.starts_with("humidity") && key.ends_with("_input") {
        return Some(format!("{value} ({:.2} %RH)", raw as f64 / 1000.0));
    }

    None
}

fn format_power_supply_value(key: &str, value: &str) -> Option<String> {
    let raw = value.trim().parse::<i64>().ok()?;

    if key == "capacity" {
        return Some(format!("{value} %"));
    }
    if key.starts_with("energy_") {
        return Some(format!("{value} ({:.3} Wh)", raw as f64 / 1_000_000.0));
    }
    if key.starts_with("charge_") {
        return Some(format!("{value} ({:.3} Ah)", raw as f64 / 1_000_000.0));
    }
    if key.starts_with("voltage_") {
        return Some(format!("{value} ({:.3} V)", raw as f64 / 1_000_000.0));
    }
    if key.starts_with("current_") {
        return Some(format!("{value} ({:.3} A)", raw as f64 / 1_000_000.0));
    }
    if key.starts_with("power_") {
        return Some(format!("{value} ({:.3} W)", raw as f64 / 1_000_000.0));
    }

    None
}

fn format_bytes(bytes: u64) -> String {
    const KIB: f64 = 1024.0;
    const MIB: f64 = KIB * 1024.0;
    const GIB: f64 = MIB * 1024.0;
    const TIB: f64 = GIB * 1024.0;
    let value = bytes as f64;

    if value >= TIB {
        format!("{:.2} TiB", value / TIB)
    } else if value >= GIB {
        format!("{:.2} GiB", value / GIB)
    } else if value >= MIB {
        format!("{:.2} MiB", value / MIB)
    } else if value >= KIB {
        format!("{:.2} KiB", value / KIB)
    } else {
        format!("{bytes} B")
    }
}

fn format_bits_per_second(bits: u64) -> String {
    let value = bits as f64;
    if value >= 1_000_000_000.0 {
        format!("{:.2} Gbit/s", value / 1_000_000_000.0)
    } else if value >= 1_000_000.0 {
        format!("{:.2} Mbit/s", value / 1_000_000.0)
    } else if value >= 1_000.0 {
        format!("{:.2} kbit/s", value / 1_000.0)
    } else {
        format!("{bits} bit/s")
    }
}

fn processor_architecture_name(code: u32) -> Option<&'static str> {
    match code {
        0 => Some("x86"),
        1 => Some("MIPS"),
        2 => Some("Alpha"),
        3 => Some("PowerPC"),
        5 => Some("ARM"),
        6 => Some("IA64 / Itanium"),
        9 => Some("x64"),
        12 => Some("ARM64"),
        _ => None,
    }
}

fn cim_memory_type_name(code: u32) -> Option<&'static str> {
    match code {
        0 => Some("Unknown"),
        1 => Some("Other"),
        2 => Some("DRAM"),
        3 => Some("Synchronous DRAM"),
        4 => Some("Cache DRAM"),
        5 => Some("EDO"),
        6 => Some("EDRAM"),
        7 => Some("VRAM"),
        8 => Some("SRAM"),
        9 => Some("RAM"),
        10 => Some("ROM"),
        11 => Some("Flash"),
        12 => Some("EEPROM"),
        13 => Some("FEPROM"),
        14 => Some("EPROM"),
        15 => Some("CDRAM"),
        16 => Some("3DRAM"),
        17 => Some("SDRAM"),
        18 => Some("SGRAM"),
        19 => Some("RDRAM"),
        20 => Some("DDR"),
        21 => Some("DDR2"),
        22 => Some("DDR2 FB-DIMM"),
        24 => Some("DDR3"),
        25 => Some("FBD2"),
        26 => Some("DDR4"),
        27 => Some("LPDDR"),
        28 => Some("LPDDR2"),
        29 => Some("LPDDR3"),
        30 => Some("LPDDR4"),
        31 => Some("Logical non-volatile device"),
        32 => Some("HBM"),
        33 => Some("HBM2"),
        34 => Some("DDR5"),
        35 => Some("LPDDR5"),
        36 => Some("HBM3"),
        _ => None,
    }
}

fn smbios_memory_type_name(code: u32) -> Option<&'static str> {
    match code {
        1 => Some("Other"),
        2 => Some("Unknown"),
        3 => Some("DRAM"),
        4 => Some("EDRAM"),
        5 => Some("VRAM"),
        6 => Some("SRAM"),
        7 => Some("RAM"),
        8 => Some("ROM"),
        9 => Some("Flash"),
        10 => Some("EEPROM"),
        11 => Some("FEPROM"),
        12 => Some("EPROM"),
        13 => Some("CDRAM"),
        14 => Some("3DRAM"),
        15 => Some("SDRAM"),
        16 => Some("SGRAM"),
        17 => Some("RDRAM"),
        18 => Some("DDR"),
        19 => Some("DDR2"),
        20 => Some("DDR2 FB-DIMM"),
        24 => Some("DDR3"),
        25 => Some("FBD2"),
        26 => Some("DDR4"),
        27 => Some("LPDDR"),
        28 => Some("LPDDR2"),
        29 => Some("LPDDR3"),
        30 => Some("LPDDR4"),
        31 => Some("Logical non-volatile device"),
        32 => Some("HBM"),
        33 => Some("HBM2"),
        34 => Some("DDR5"),
        35 => Some("LPDDR5"),
        36 => Some("HBM3"),
        _ => None,
    }
}

fn memory_form_factor_name(code: u32) -> Option<&'static str> {
    match code {
        0 => Some("Unknown"),
        1 => Some("Other"),
        2 => Some("SIP"),
        3 => Some("DIP"),
        4 => Some("ZIP"),
        5 => Some("SOJ"),
        6 => Some("Proprietary"),
        7 => Some("SIMM"),
        8 => Some("DIMM"),
        9 => Some("TSOP"),
        10 => Some("PGA"),
        11 => Some("RIMM"),
        12 => Some("SODIMM"),
        13 => Some("SRIMM"),
        14 => Some("SMD"),
        15 => Some("SSMP"),
        16 => Some("QFP"),
        17 => Some("TQFP"),
        18 => Some("SOIC"),
        19 => Some("LCC"),
        20 => Some("PLCC"),
        21 => Some("BGA"),
        22 => Some("FPBGA"),
        23 => Some("LGA"),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{DeviceRecord, ReportMeta, Section, SystemReport};

    fn sample_report() -> SystemReport {
        let mut cpu = Section::new("CPU");
        cpu.push(DeviceRecord::new("CPU 0").with_field("Model", "Example CPU"));
        SystemReport {
            meta: ReportMeta {
                schema_version: 1,
                app_name: "HowAmI".into(),
                app_version: "0.1.0".into(),
                generated_at: "2026-01-01T00:00:00+00:00".into(),
                os: "test".into(),
                architecture: "x86_64".into(),
                elevated: true,
                privacy_notice: "test".into(),
            },
            sections: vec![cpu],
            warnings: vec![],
        }
    }

    #[test]
    fn text_report_contains_core_fields() {
        let text = render_text(&sample_report());
        assert!(text.contains("HowAmI"));
        assert!(text.contains("Report Schema        : 1"));
        assert!(text.contains("Example CPU"));
        assert!(text.contains("Collection Privilege : Administrator / root"));
    }

    #[test]
    fn formats_byte_counts_for_people() {
        assert_eq!(
            display_value("GPU Memory (Registry)", "VRAMBytes", "8589934592"),
            "8589934592 (8.00 GiB)"
        );
        assert_eq!(
            display_value("Storage", "size", "1099511627776"),
            "1099511627776 (1.00 TiB)"
        );
    }

    #[test]
    fn formats_network_rates() {
        assert_eq!(
            display_value("Network Adapters", "SpeedBitsPerSecond", "1000000000"),
            "1000000000 (1.00 Gbit/s)"
        );
        assert_eq!(
            display_value("Network Adapters", "speed", "2500"),
            "2500 Mbit/s (2.50 Gbit/s)"
        );
    }

    #[test]
    fn formats_linux_sensor_units() {
        assert_eq!(
            display_value("Hardware Sensors / hwmon", "temp1_input", "42500"),
            "42500 (42.50 °C)"
        );
        assert_eq!(
            display_value("Power / Battery", "energy_full", "60000000"),
            "60000000 (60.000 Wh)"
        );
    }

    #[test]
    fn labels_common_windows_hardware_codes() {
        assert_eq!(display_value("CPU", "ArchitectureCode", "9"), "9 (x64)");
        assert_eq!(
            display_value("Memory", "SMBIOSMemoryTypeCode", "34"),
            "34 (DDR5)"
        );
        assert_eq!(
            display_value("Memory", "FormFactorCode", "12"),
            "12 (SODIMM)"
        );
    }
}
